### ISSUE TITLE
Add this project to the awesome-harbor list

### ISSUE THREAD

**Issue by Vad1mo** [hinyinlam-pivotal/harbor-cli#3]
This is an outstanding project. I think it is a perfect candidate to add it to the https://github.com/container-registry/awesome-harbor.

**Comment by hinyinlam** [comment]
Hi @Vad1mo would be great to know if a PR will the easiest way to add the CLI to the https://github.com/container-registry/awesome-harbor ?

Let's move this discussion to https://github.com/hinyinlam/cli-for-harbor
