### ISSUE TITLE
Compatibility with harbor 1.10

### ISSUE THREAD

**Issue by thuzzik** [hinyinlam-pivotal/harbor-cli#4]
Hello, is this cli compatible with harbor 1.10?

Thanks

**Comment by hinyinlam** [comment]
hi @thuzzik A new version of binary of Harbor CLI (unofficial) has been released, please visit this repo URL: https://github.com/hinyinlam/cli-for-harbor

The CLI only support V2 API from Harbor, thus the legacy API is not in the scope of support of this CLI.

I'll advise to move this question to the https://github.com/hinyinlam/cli-for-harbor repo

At the same time, I'm renaming and archiving this repo for the favor of the binary version, thank you for your involvement in contributing the idea!
